name: localization_parser
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^2.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.1
  csv: ^5.0.1
  gsheets: ^0.4.2
